all:
	g++ teste_ponto.cpp -o teste_ponto
	g++ teste_vetor.cpp -o teste_vetor
	g++ teste_circunferencia.cpp -o teste_circunferencia
	g++ teste_retangulo.cpp -o teste_retangulo
	g++ teste_triangulo.cpp -o teste_triangulo
	g++ teste_objeto.cpp -o teste_objeto

clean:
	rm teste_ponto teste_vetor teste_circunferencia teste_retangulo teste_triangulo teste_objeto